#!/usr/bin/env python3
"""Build Windows installer with Inno Setup."""

import argparse
import os
import subprocess
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
sys.path.insert(0, os.path.join(ROOT, "src"))

from luxelead.release_pack import find_launch_exe, find_onedir_folder

INNO_CANDIDATES = (
    os.path.expandvars(r"%LOCALAPPDATA%\Programs\Inno Setup 6\ISCC.exe"),
    r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe",
    r"C:\Program Files\Inno Setup 6\ISCC.exe",
)


def find_inno_compiler() -> str:
    for path in INNO_CANDIDATES:
        if os.path.isfile(path):
            return path
    return ""


def write_inno_script(
    iss_path: str,
    onedir_dir: str,
    launch_exe: str,
    version: str,
    display_version: str,
    output_dir: str,
) -> str:
    onedir_dir = os.path.abspath(onedir_dir).replace("/", "\\")
    output_dir = os.path.abspath(output_dir).replace("/", "\\")
    output_base = f"LuxeLead_Setup_V{version}"
    app_name = f"LuxeLead PPT Generator {display_version}"

    content = f"""; Auto-generated by scripts/build_installer.py
#define AppVersion "{version}"
#define AppDisplayName "{app_name}"
#define LaunchExe "{launch_exe}"
#define SourceDir "{onedir_dir}"
#define OutputDir "{output_dir}"
#define OutputBase "{output_base}"

[Setup]
AppId={{{{A1B2C3D4-E5F6-7890-ABCD-EF1234567890}}}}
AppName={{#AppDisplayName}}
AppVersion={{#AppVersion}}
AppVerName={{#AppDisplayName}}
DefaultDirName={{autopf}}\\LuxeLead
DefaultGroupName=LuxeLead
DisableProgramGroupPage=no
OutputDir={{#OutputDir}}
OutputBaseFilename={{#OutputBase}}
Compression=lzma2/normal
SolidCompression=no
DiskSpanning=no
WizardStyle=modern
ArchitecturesAllowed=x64compatible
ArchitecturesInstallIn64BitMode=x64compatible
UninstallDisplayIcon={{app}}\\{{#LaunchExe}}

[Languages]
Name: "chinesesimplified"; MessagesFile: "compiler:Languages\\ChineseSimplified.isl"

[Tasks]
Name: "desktopicon"; Description: "创建桌面快捷方式"; GroupDescription: "附加选项:"; Flags: unchecked

[Files]
Source: "{{#SourceDir}}\\*"; DestDir: "{{app}}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{{group}}\\LuxeLead PPT"; Filename: "{{app}}\\{{#LaunchExe}}"
Name: "{{autodesktop}}\\LuxeLead PPT"; Filename: "{{app}}\\{{#LaunchExe}}"; Tasks: desktopicon

[Run]
Filename: "{{app}}\\{{#LaunchExe}}"; Description: "启动 LuxeLead"; Flags: nowait postinstall skipifsilent
"""
    os.makedirs(os.path.dirname(os.path.abspath(iss_path)), exist_ok=True)
    with open(iss_path, "w", encoding="utf-8-sig", newline="\r\n") as handle:
        handle.write(content)
    return os.path.join(output_dir, f"{output_base}.exe")


def main() -> int:
    parser = argparse.ArgumentParser(description="生成 Inno Setup 安装包")
    parser.add_argument("--dist", default=os.path.join(ROOT, "dist"))
    parser.add_argument("--version", required=True)
    parser.add_argument("--display-version", default="")
    parser.add_argument("--output-dir", default=os.path.join(ROOT, "dist", "release"))
    parser.add_argument("--iss-only", action="store_true", help="仅生成 .iss，不调用 ISCC")
    args = parser.parse_args()

    onedir_dir = find_onedir_folder(args.dist, args.version)
    launch_exe = find_launch_exe(onedir_dir)
    display_version = args.display_version or f"测试版V{args.version}"
    iss_path = os.path.join(ROOT, "installer", f"LuxeLead_V{args.version}.iss")
    setup_exe = write_inno_script(
        iss_path,
        onedir_dir,
        launch_exe,
        args.version,
        display_version,
        args.output_dir,
    )
    print("[OK] iss:", iss_path)
    print("[OK] expected setup:", setup_exe)

    if args.iss_only:
        return 0

    iscc = find_inno_compiler()
    if not iscc:
        print("[WARN] 未找到 Inno Setup 6 (ISCC.exe)，已仅生成 .iss 脚本")
        print("       请安装 Inno Setup 后执行:", iscc or "ISCC.exe", iss_path)
        return 0

    result = subprocess.run([iscc, iss_path], cwd=ROOT)
    if result.returncode != 0:
        print("[ERROR] ISCC 编译失败", file=sys.stderr)
        return result.returncode
    if os.path.isfile(setup_exe):
        print("[OK] setup exe:", setup_exe)
    else:
        print("[WARN] 未找到输出文件:", setup_exe)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
